version: 2
jobs:
  build:
    docker:
      # specify version
      - image: circleci/openjdk:17.0-jdk-buster-browsers

    working_directory: ~/repo

    environment:
      # Customize the JVM heap
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      # run test
      - run: mvn integration-test